# Generated by Django 2.2.17 on 2021-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0002_auto_20210319_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
