# Generated by Django 2.2.17 on 2021-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0003_dessert_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
