# Generated by Django 2.2.17 on 2021-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0005_remove_dessert_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='picture',
            field=models.ImageField(blank=True, upload_to='shop_images'),
        ),
    ]
