# Generated by Django 2.2.17 on 2021-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0008_auto_20210403_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
