# Generated by Django 2.2.17 on 2021-04-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0009_auto_20210403_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.FloatField(),
        ),
    ]
