# Generated by Django 2.2.17 on 2021-04-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessertreview', '0010_auto_20210403_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='views',
        ),
    ]
